config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  has_and_belongs_to_many :products
  validates :name, :street, :number, :city, :country, :zip_code, presence: true
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :street, :number, :zip_code, :city, :country)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :street %>
    <%= form.text_field :street, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, class: "form-control" %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :city %>
      <%= form.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= form.label :country %>
      <%= form.text_field :country, class: "form-control" %>
    </div>
    <div class="form-group col-md-2">
      <%= form.label :zip_code %>
      <%= form.text_field :zip_code, class: "form-control" %>
    </div>
  </div>
  <%= form.submit "Submit Store", class: "btn btn-primary" %>
<% end %>

app/views/stores/edit.html.erb
<h1 class="mt-3">Store</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class="mb-3">Edit.</span>
</p>

<div class="d-flex justify-content-start mb-3">
  <%= link_to "❮ Back", stores_path, class: "card-link" %>
</div>

<%= render 'form', store: @store %>

<br>

<%= link_to 'Show', @store %>

app/views/stores/index.html.erb
<h1 class="mt-3">Stores.</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class="mb-3">Here manage your stores.</span>
  <%= link_to 'New Store', new_store_path, class: "btn btn-outline-primary" %>
</p>

<% unless notice.blank? %>
  <div id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="list-group list-group-flush">
  <% @stores.each do |store| %>
    <span class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= store.name %></h5>
      </div>
      <small>
        <%= store.street %>, <%= store.number %>, <%= store.zip_code %>
      </small>
      <p class="d-flex w-100 justify-content-between mb-1">
        <span>
          <%= store.city %>, <%= store.country %>
        </span>
        <span class="list-actions">
          <%= link_to 'Show', store, class: "ml-3" %>
          <%= link_to 'Edit', edit_store_path(store), class: "ml-3" %>
          <%= link_to 'Destroy', store, class: "ml-3", method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      </p>
    </span>
  <% end %>
</div>

<br>

app/views/stores/new.html.erb
<h1 class="mt-3">Store</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class="mb-3">Create a new store.</span>
</p>

<div class="d-flex justify-content-start mb-3">
  <%= link_to "❮ Back", stores_path, class: "card-link" %>
</div>

<%= render 'form', store: @store %>

<br>

app/views/stores/show.html.erb
<h1 class="mt-3">Store.</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class="mb-3">Details.</span>
</p>

<% unless notice.blank? %>
  <div id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="d-flex justify-content-start mb-3">
  <%= link_to "❮ Back", stores_path, class: "card-link" %>
</div>

<div class="d-flex justify-content-center">
  <div class="card mb-3" style="width: 100%;">
    <div class="card-body">
      <h5 class="card-title"><%= @store.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <strong>Address:</strong> <br>
        <%= @store.street %>, <%= @store.number %>, <%= @store.zip_code %>
      </h6>
      <p class="card-text">
        <%= @store.city %>, <%= @store.country %>
      </p>
      <%= link_to 'Edit', edit_store_path(@store), class: "card-link" %>
    </div>
  </div>
</div>

<% if @store.products.any? %>
  <p>Products available in this store:</p>

  <div class="list-group list-group-flush">
    <% @store.products.each do |product| %>
      <span class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= product.name %></h5>
          <span class="badge badge-primary badge-pill">
            $ <%= product.price %>
          </span>
        </div>
        <small>
          Color: <%= product.color %> | Size: <%= product.size %>
        </small>
        <p class="d-flex w-100 justify-content-between mb-1">
          <span>
            <strong>Category:</strong> <%= product.category.name %>
          </span>
          <span class="list-actions" style="min-width: 65px;">
            <%= link_to 'Show', product, class: "ml-3" %>
          </span>
        </p>
      </span>
    <% end %>
  </div>
<% else %>
  <p>
    <strong>Note:</strong> There is no products assosieted to this store.
  </p>
<% end %>

<br>