config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :products
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :keywords, dependent: :destroy
  validates_associated :keywords
  validates :name, presence:true, uniqueness: { case_sensitive: false }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    respond_to do |format|
      format.html
      format.js
    end
    
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    params[:category][:keywords_list].split(',').each do |name|
      unless name.empty?
        keyword = Keyword.find_by name: name.to_s.strip
        if !keyword
          @category.keywords << Keyword.new(name: name.to_s.strip)
        else
          respond_to do |format|
            format.html { redirect_to :categories, :flash => { :error => "Category not saved, keyword *#{name.to_s.strip}* is already in use!" } and return }
            format.json { render :categories, status: :created, location: @categories }
          end
        end
      end
    end

    respond_to do |format|
      if @category.save
        format.html { redirect_to :categories, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.js { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    params[:category][:keywords_list].split(',').each do |name|
      unless name.empty?
        keyword = Keyword.find_by name: name.to_s.strip
        if !keyword
          @category.keywords << Keyword.new(name: name.to_s.strip)
        else
          respond_to do |format|
            format.html { redirect_to @category, :flash => { :error => "Category not updated, keyword *#{name.to_s.strip}* is already in use!" } and return }
            format.json { render :show, status: :ok, location: @category }
          end
        end
      end
    end

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Editing Category</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= render 'form', category: @category %>
</div>

app/views/categories/_form.html.erb
<div class="container mt-4">
  <%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :keywords, "Keywords (comma separated)" %>
      <%= form.text_field "keywords_list", :value => @category.keywords.map(&:name).join(', ') , class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit "Create Category", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/categories/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalLabel">Create a new category.</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= render 'form', category: @category %>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<br>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/edit.js.erb
$("#modal-window .modal-content").html("<%= j (render 'categories/edit') %>");
$("#modal-window").modal('show');

app/views/categories/index.html.erb
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

<h1 class="cover-heading">Categories.</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class=" mb-3">Here manage your categories.</span>
  <%= link_to 'New Category', { controller => :categories, :action =>:new ,:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'  }, class: "btn btn-outline-primary" %>
</p>

<% unless notice.blank? %>
  <div id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if flash[:error] %>
  <div id="error" class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<% if @categories.any? %>
<div class="list-group list-group-flush">
  <% @categories.each do |category| %>
    <span class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= category.name %></h5>
      </div>
      <p class="d-flex w-100 justify-content-between mb-1">
        <span>
          <strong>Keywords:</strong>
          <%= category.keywords.map(&:name).join(', ') %>
        </span>
        <span class="list-actions">
          <%= link_to 'Show', category, class: "ml-3" %>
          <%= link_to 'Edit', edit_category_path(category), remote: true, class: "ml-3" %>
          <%= link_to 'Destroy', category, class: "ml-3", method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      </p>
    </span>
  <% end %>
</div>
<% else %>
  <p>There is no categories. Create one!</p>
<% end %>

<br>

app/views/categories/new.html.erb
<h1 class="mt-3">New Category</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class=" mb-3">Create a new category.</span>
</p>

<%= render 'form', category: @category %>

<br>

<%= link_to 'Back', categories_path %>

app/views/categories/new.js.erb
$("#modal-window .modal-content").html("<%= j (render 'categories/new') %>");
$("#modal-window").modal('show');

app/views/categories/show.html.erb
<h1 class="mt-3">Category.</h1>
<p class="lead d-flex w-100 flex-wrap justify-content-between align-items-center mb-3">
  <span class="mb-3">Details.</span>
</p>

<% unless notice.blank? %>
  <div id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if flash[:error] %>
  <div id="error" class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

<div class="d-flex justify-content-start mb-3">
  <%= link_to "❮ Back", categories_path, class: "card-link" %>
</div>

<div class="d-flex justify-content-center">
  <div class="card mb-3" style="width: 100%;">
    <div class="card-body">
      <h5 class="card-title"><%= @category.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <strong>Keywords:</strong>
        <% @category.keywords.each do | keyword | %>
          <span class="badge badge-light"><%= keyword.name %></span>
        <% end %>
      </h6>
      <%= link_to 'Edit', edit_category_path(@category), class: "card-link" %>
    </div>
  </div>
</div>

<% if @category.products.any? %>
  <p>Products available in this category:</p>

  <div class="list-group list-group-flush">
    <% @category.products.each do |product| %>
      <span class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= product.name %></h5>
          <span class="badge badge-primary badge-pill">
            $ <%= product.price %>
          </span>
        </div>
        <small>
          Color: <%= product.color %> | Size: <%= product.size %>
        </small>
        <p class="d-flex w-100 justify-content-between mb-1">
          <span>
            <strong>Category:</strong> <%= product.category.name %>
          </span>
          <span class="list-actions">
            <%= link_to 'Show', product, class: "ml-3" %>
          </span>
        </p>
      </span>
    <% end %>
  </div>
<% else %>
  <p>
    <strong>Note:</strong> There is no products assosieted to this category.
  </p>
<% end %>

<br>